In [1]:
# numpy : deal with numerical data. Arrays. 1x1, 2x2, nxn ... dimensional arrays
# pandas: to represent data in rows and columns format.  Read/write/edit data using powerful data frames, source of data could be file, api, database
# matplotlib or seaborn :  used to plot the data in the of pictorial/graphs. 
# scikit learn:  to access common utilities and models. 


In [2]:
# Windows:  install numpy package
!pip install numpy

In [3]:
# Linux/Unix: get-pip.py
# curl "url of get-pip.py" -o get-pip.py
#python get-pip.py

In [4]:
!pip install numpy23434343434445

ERROR: Could not find a version that satisfies the requirement numpy23434343434445 (from versions: none)
ERROR: No matching distribution found for numpy23434343434445


In [5]:
# Mac: 
# Step 1: install easy_install
# curl https://bootstrap.pypa.io/ez_setup.py -o - | sudo python
# Step 2: sudo easy_install pip
# step 3: install actual module
# pip install numpy



In [1]:
import numpy as np

In [9]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}, optional
        Specify the memory layout of the array. If object is not an array, the
        newly crea

In [ ]:
# array index start with zero 0


In [10]:
# 1D array  [1,2,3]

oneD_array = np.array([1,2,3])

In [11]:
print(oneD_array)

[1 2 3]


In [12]:
print(oneD_array[0])

1


In [13]:
print(len(oneD_array))

3


In [16]:
np_2d = np.array([(1,2,3), (4,5,6)], dtype = float)

In [17]:
print(np_2d)

[[1. 2. 3.]
 [4. 5. 6.]]


In [21]:
np_2d_2 = np.array([[(1,2,3), (4,5,6)], [(1,2,3), (4,5,6)]], dtype = float)

In [22]:
print(np_2d_2)

[[[1. 2. 3.]
  [4. 5. 6.]]

 [[1. 2. 3.]
  [4. 5. 6.]]]


In [23]:
np_3d = np.array([(1,2,3), (4,5,6), (7,8,9)], dtype=float)

In [24]:
print(np_3d)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [25]:
print(np_3d[0,0])

1.0


In [26]:
print(np_3d[0,1])

2.0


In [27]:
print(np_3d[1,0])

4.0


In [28]:
print(np_3d[2,0])

7.0


In [29]:
np_nd_1 = np.zeros((5, 6))

In [30]:
display(np_nd_1)

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [31]:
np_nd_2 = np.zeros((15, 26))

In [32]:
display(np_nd_2)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 

In [34]:
np_nd_ones_1 = np.ones((2,3), dtype = np.int16)

In [35]:
display(np_nd_ones_1)

array([[1, 1, 1],
       [1, 1, 1]], dtype=int16)

In [37]:
np_nd_ones_2 = np.ones((2,3, 4), dtype = float)

In [38]:
print(np_nd_ones_2)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [42]:
np_step_nd_1 = np.arange(10, 26, 5)

In [43]:
print(np_step_nd_1)

[10 15 20 25]


In [45]:
np_step_nd_2 = np.arange(2, 50, 2)

In [46]:
print(np_step_nd_2)

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


In [50]:
np_linspace_nd_1 = np.linspace(1, 5, 9)

In [51]:
print(np_linspace_nd_1)

[1.  1.5 2.  2.5 3.  3.5 4.  4.5 5. ]


In [56]:
np_linspace_nd_2 = np.linspace(1, 50, 5)  # 5 elements between 1 to 50 

In [55]:
print(np_linspace_nd_2)

[ 1.         17.33333333 33.66666667 50.        ]


In [57]:
np_custom_nd_1 = np.full((2,4), 3)

In [58]:
print(np_custom_nd_1)

[[3 3 3 3]
 [3 3 3 3]]


In [2]:
np_eye_3d_1 = np.eye(3)

In [3]:
display(np_eye_3d_1)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [4]:
np_empty_nd_1 = np.empty((3,6))

In [5]:
display(np_empty_nd_1)

array([[6.23042070e-307, 3.56043053e-307, 1.60219306e-306,
        7.56571288e-307, 1.89146896e-307, 1.37961302e-306],
       [1.05699242e-307, 8.01097889e-307, 1.78020169e-306,
        7.56601165e-307, 1.02359984e-306, 1.33510679e-306],
       [2.22522597e-306, 1.60220393e-306, 8.90094053e-307,
        9.34607074e-307, 2.22523140e-306, 8.34451503e-308]])

In [7]:
np_random_6x8_1 = np.random.random((6, 8))

In [8]:
print(np_random_6x8_1)

[[0.18704476 0.20188462 0.62512229 0.00689303 0.08918378 0.30600921
  0.05759548 0.02093624]
 [0.51374887 0.00257786 0.28088062 0.6204107  0.79303692 0.60972776
  0.86753525 0.65395021]
 [0.52614866 0.68894576 0.56803806 0.82808012 0.64807676 0.08288524
  0.03661304 0.93459638]
 [0.5507935  0.83131672 0.43207841 0.74815054 0.97707504 0.58990424
  0.43100072 0.58257829]
 [0.69864898 0.21618879 0.63876268 0.52773437 0.6266714  0.23382161
  0.91524431 0.32971149]
 [0.48954591 0.05742736 0.08313607 0.93187253 0.33911314 0.8523761
  0.76191057 0.54088744]]


In [9]:
np_random_3x4_1 = np.random.random((3, 4))

In [10]:
print(np_random_3x4_1)

[[0.39351869 0.24955335 0.8418716  0.12903614]
 [0.34731577 0.74824616 0.10966537 0.4492169 ]
 [0.73875586 0.50368077 0.27163779 0.65388485]]


In [11]:
# typical n dimensional array format [[row1], [row2], [row3]]
# row1 of size (1x6) look like below
# [1,2,3,4,5,6]

In [12]:
# perform basic operations on Array

# to know exact size of an array 
display(np_empty_nd_1.shape)


(3, 6)

In [14]:
# unit test using assert framework

# % of accuracy : 99.9999999999999999999999999999999999999999999999999999999999999999999
# performance : real time traffic analysis using deep learning. 

# vvv: volume, variety, velocity:  
# metadata: 

display(np_random_6x8_1.shape)

(6, 8)

In [15]:
display(len(np_random_6x8_1))

6

In [16]:
display(np_random_6x8_1.ndim)

2

In [17]:
display(np_random_6x8_1.size)

48

In [18]:
display(np_empty_nd_1.size)

18

In [19]:
# different data types of an array can be defined using dtype

# np_2d_2 = np.array([[(1,2,3), (4,5,6)], [(1,2,3), (4,5,6)]], dtype = float)

# Integer 64 bit  ---- np.int64
# float  32 bit   ---- np.float32
# boolean         ---- np.bool
# string          ---- np.string
# python object   ---- np.object
# complex         ---- np.complex
# unicode         ---- np.unicode_


In [20]:
display(np_random_6x8_1.dtype)

dtype('float64')

In [21]:
display(np_random_6x8_1.dtype.name)

'float64'